# AUTO-GENERATED by scratch/extract_city_eui.py
# Source: ems_transformer E0 baseline (gcs_download/all_metadata.jsonl)
# DO NOT EDIT MANUALLY — re-run extract_city_eui.py to regenerate
#
# 150개 조합 (15 building × 10 city)
# EUI 단위: kWh/m²·yr

CITY_EUI_BASE: dict[tuple[str, str], dict] = {
    # Apartment
    ("Apartment", "Busan"): {"median": 196.9, "p10": 142.4, "p90": 256.2, "n": 1319},
    ("Apartment", "Cheongju"): {"median": 198.2, "p10": 142.3, "p90": 254.7, "n": 1175},
    ("Apartment", "Daegu"): {"median": 197.5, "p10": 143.8, "p90": 252.0, "n": 1182},
    ("Apartment", "Daejeon"): {"median": 200.2, "p10": 142.5, "p90": 257.5, "n": 1376},
    ("Apartment", "Gangneung"): {"median": 198.2, "p10": 144.9, "p90": 247.6, "n": 892},
    ("Apartment", "Gwangju"): {"median": 199.8, "p10": 143.2, "p90": 256.6, "n": 1186},
    ("Apartment", "Incheon"): {"median": 195.3, "p10": 144.8, "p90": 246.4, "n": 1125},
    ("Apartment", "Jeju"): {"median": 197.9, "p10": 146.2, "p90": 250.9, "n": 1166},
    ("Apartment", "Seoul"): {"median": 198.2, "p10": 139.6, "p90": 255.7, "n": 1407},
    ("Apartment", "Ulsan"): {"median": 200.4, "p10": 143.7, "p90": 256.3, "n": 1311},

    # FullServiceRestaurant
    ("FullServiceRestaurant", "Busan"): {"median": 491.7, "p10": 466.7, "p90": 518.3, "n": 5300},
    ("FullServiceRestaurant", "Cheongju"): {"median": 485.9, "p10": 461.6, "p90": 511.6, "n": 5300},
    ("FullServiceRestaurant", "Daegu"): {"median": 485.7, "p10": 462.0, "p90": 511.4, "n": 5300},
    ("FullServiceRestaurant", "Daejeon"): {"median": 491.1, "p10": 466.3, "p90": 517.1, "n": 5300},
    ("FullServiceRestaurant", "Gangneung"): {"median": 480.1, "p10": 456.2, "p90": 504.6, "n": 5300},
    ("FullServiceRestaurant", "Gwangju"): {"median": 503.0, "p10": 476.7, "p90": 530.8, "n": 5300},
    ("FullServiceRestaurant", "Incheon"): {"median": 482.4, "p10": 458.1, "p90": 506.8, "n": 5300},
    ("FullServiceRestaurant", "Jeju"): {"median": 501.5, "p10": 476.2, "p90": 528.6, "n": 5300},
    ("FullServiceRestaurant", "Seoul"): {"median": 492.8, "p10": 467.3, "p90": 519.0, "n": 5300},
    ("FullServiceRestaurant", "Ulsan"): {"median": 487.9, "p10": 463.2, "p90": 513.8, "n": 5300},

    # Hospital
    ("Hospital", "Busan"): {"median": 269.8, "p10": 245.6, "p90": 296.8, "n": 990},
    ("Hospital", "Cheongju"): {"median": 267.1, "p10": 240.7, "p90": 293.2, "n": 1086},
    ("Hospital", "Daegu"): {"median": 269.1, "p10": 246.4, "p90": 293.7, "n": 843},
    ("Hospital", "Daejeon"): {"median": 268.7, "p10": 245.1, "p90": 295.4, "n": 1138},
    ("Hospital", "Gangneung"): {"median": 273.6, "p10": 249.3, "p90": 297.0, "n": 753},
    ("Hospital", "Gwangju"): {"median": 270.3, "p10": 246.5, "p90": 297.5, "n": 1155},
    ("Hospital", "Incheon"): {"median": 266.5, "p10": 243.7, "p90": 291.5, "n": 856},
    ("Hospital", "Jeju"): {"median": 267.6, "p10": 244.8, "p90": 292.7, "n": 868},
    ("Hospital", "Seoul"): {"median": 268.1, "p10": 242.9, "p90": 295.0, "n": 1144},
    ("Hospital", "Ulsan"): {"median": 269.8, "p10": 245.5, "p90": 295.4, "n": 1064},

    # Hotel
    ("Hotel", "Busan"): {"median": 201.7, "p10": 169.2, "p90": 237.0, "n": 3269},
    ("Hotel", "Cheongju"): {"median": 200.5, "p10": 166.7, "p90": 233.0, "n": 2519},
    ("Hotel", "Daegu"): {"median": 200.5, "p10": 167.6, "p90": 233.5, "n": 3287},
    ("Hotel", "Daejeon"): {"median": 201.2, "p10": 168.5, "p90": 236.7, "n": 3199},
    ("Hotel", "Gangneung"): {"median": 200.2, "p10": 168.3, "p90": 232.0, "n": 2606},
    ("Hotel", "Gwangju"): {"median": 203.6, "p10": 170.9, "p90": 238.9, "n": 2642},
    ("Hotel", "Incheon"): {"median": 199.0, "p10": 167.7, "p90": 232.1, "n": 3114},
    ("Hotel", "Jeju"): {"median": 202.1, "p10": 169.3, "p90": 237.7, "n": 3455},
    ("Hotel", "Seoul"): {"median": 201.5, "p10": 169.4, "p90": 236.3, "n": 3469},
    ("Hotel", "Ulsan"): {"median": 200.8, "p10": 168.6, "p90": 234.5, "n": 3578},

    # LargeOffice
    ("LargeOffice", "Busan"): {"median": 182.2, "p10": 168.1, "p90": 196.4, "n": 3862},
    ("LargeOffice", "Cheongju"): {"median": 179.3, "p10": 165.6, "p90": 193.6, "n": 3004},
    ("LargeOffice", "Daegu"): {"median": 179.3, "p10": 166.1, "p90": 192.9, "n": 2698},
    ("LargeOffice", "Daejeon"): {"median": 181.5, "p10": 167.2, "p90": 195.7, "n": 3888},
    ("LargeOffice", "Gangneung"): {"median": 180.7, "p10": 167.6, "p90": 193.8, "n": 2137},
    ("LargeOffice", "Gwangju"): {"median": 183.9, "p10": 169.5, "p90": 197.9, "n": 2957},
    ("LargeOffice", "Incheon"): {"median": 179.3, "p10": 165.9, "p90": 192.6, "n": 2461},
    ("LargeOffice", "Jeju"): {"median": 183.1, "p10": 167.9, "p90": 197.1, "n": 3110},
    ("LargeOffice", "Seoul"): {"median": 180.7, "p10": 166.2, "p90": 194.6, "n": 3514},
    ("LargeOffice", "Ulsan"): {"median": 180.2, "p10": 165.8, "p90": 194.3, "n": 3564},

    # MediumOffice
    ("MediumOffice", "Busan"): {"median": 168.3, "p10": 165.9, "p90": 172.2, "n": 3909},
    ("MediumOffice", "Cheongju"): {"median": 171.9, "p10": 168.7, "p90": 176.7, "n": 3566},
    ("MediumOffice", "Daegu"): {"median": 169.8, "p10": 167.0, "p90": 174.4, "n": 4029},
    ("MediumOffice", "Daejeon"): {"median": 173.5, "p10": 170.4, "p90": 178.6, "n": 4416},
    ("MediumOffice", "Gangneung"): {"median": 168.6, "p10": 165.9, "p90": 173.0, "n": 3946},
    ("MediumOffice", "Gwangju"): {"median": 173.9, "p10": 170.8, "p90": 179.8, "n": 4003},
    ("MediumOffice", "Incheon"): {"median": 170.1, "p10": 167.1, "p90": 174.8, "n": 4629},
    ("MediumOffice", "Jeju"): {"median": 171.2, "p10": 167.9, "p90": 177.5, "n": 3968},
    ("MediumOffice", "Seoul"): {"median": 173.3, "p10": 170.1, "p90": 178.3, "n": 3305},
    ("MediumOffice", "Ulsan"): {"median": 169.3, "p10": 166.7, "p90": 174.1, "n": 3926},

    # OutPatient
    ("OutPatient", "Busan"): {"median": 279.3, "p10": 262.9, "p90": 297.8, "n": 600},
    ("OutPatient", "Cheongju"): {"median": 274.4, "p10": 257.9, "p90": 292.8, "n": 787},
    ("OutPatient", "Daegu"): {"median": 277.6, "p10": 261.3, "p90": 295.2, "n": 504},
    ("OutPatient", "Daejeon"): {"median": 279.0, "p10": 259.9, "p90": 299.0, "n": 834},
    ("OutPatient", "Gangneung"): {"median": 283.0, "p10": 263.2, "p90": 298.2, "n": 443},
    ("OutPatient", "Gwangju"): {"median": 280.2, "p10": 262.7, "p90": 300.6, "n": 754},
    ("OutPatient", "Incheon"): {"median": 272.9, "p10": 256.3, "p90": 290.5, "n": 598},
    ("OutPatient", "Jeju"): {"median": 274.8, "p10": 257.1, "p90": 292.4, "n": 582},
    ("OutPatient", "Seoul"): {"median": 278.4, "p10": 260.7, "p90": 297.9, "n": 820},
    ("OutPatient", "Ulsan"): {"median": 279.5, "p10": 261.1, "p90": 296.6, "n": 595},

    # PrimarySchool
    ("PrimarySchool", "Busan"): {"median": 108.4, "p10": 99.1, "p90": 117.9, "n": 2307},
    ("PrimarySchool", "Cheongju"): {"median": 104.3, "p10": 95.5, "p90": 113.5, "n": 2125},
    ("PrimarySchool", "Daegu"): {"median": 104.0, "p10": 94.6, "p90": 113.3, "n": 2328},
    ("PrimarySchool", "Daejeon"): {"median": 107.6, "p10": 98.3, "p90": 117.2, "n": 2283},
    ("PrimarySchool", "Gangneung"): {"median": 105.8, "p10": 97.3, "p90": 115.1, "n": 2086},
    ("PrimarySchool", "Gwangju"): {"median": 110.1, "p10": 100.7, "p90": 120.1, "n": 1868},
    ("PrimarySchool", "Incheon"): {"median": 103.4, "p10": 94.9, "p90": 112.4, "n": 2355},
    ("PrimarySchool", "Jeju"): {"median": 108.7, "p10": 98.7, "p90": 118.4, "n": 2073},
    ("PrimarySchool", "Seoul"): {"median": 105.4, "p10": 96.3, "p90": 115.2, "n": 2100},
    ("PrimarySchool", "Ulsan"): {"median": 107.4, "p10": 98.4, "p90": 116.6, "n": 2232},

    # Restaurant
    ("Restaurant", "Busan"): {"median": 562.6, "p10": 538.1, "p90": 589.9, "n": 5300},
    ("Restaurant", "Cheongju"): {"median": 556.9, "p10": 532.5, "p90": 583.4, "n": 5300},
    ("Restaurant", "Daegu"): {"median": 557.9, "p10": 532.3, "p90": 584.4, "n": 5300},
    ("Restaurant", "Daejeon"): {"median": 562.0, "p10": 537.0, "p90": 589.3, "n": 5300},
    ("Restaurant", "Gangneung"): {"median": 548.9, "p10": 526.3, "p90": 574.5, "n": 5300},
    ("Restaurant", "Gwangju"): {"median": 576.0, "p10": 549.9, "p90": 605.8, "n": 5300},
    ("Restaurant", "Incheon"): {"median": 551.1, "p10": 527.6, "p90": 576.2, "n": 5300},
    ("Restaurant", "Jeju"): {"median": 572.9, "p10": 547.5, "p90": 602.2, "n": 5300},
    ("Restaurant", "Seoul"): {"median": 565.7, "p10": 540.1, "p90": 592.6, "n": 5300},
    ("Restaurant", "Ulsan"): {"median": 559.0, "p10": 533.9, "p90": 585.8, "n": 5300},

    # Retail
    ("Retail", "Busan"): {"median": 98.7, "p10": 76.7, "p90": 116.5, "n": 300},
    ("Retail", "Cheongju"): {"median": 97.7, "p10": 81.4, "p90": 114.1, "n": 5300},
    ("Retail", "Daegu"): {"median": 97.7, "p10": 75.2, "p90": 116.2, "n": 300},
    ("Retail", "Daejeon"): {"median": 99.2, "p10": 83.0, "p90": 115.2, "n": 5300},
    ("Retail", "Gangneung"): {"median": 96.7, "p10": 80.8, "p90": 112.8, "n": 5300},
    ("Retail", "Gwangju"): {"median": 100.9, "p10": 84.0, "p90": 118.6, "n": 1300},
    ("Retail", "Incheon"): {"median": 97.3, "p10": 75.5, "p90": 116.0, "n": 300},
    ("Retail", "Jeju"): {"median": 101.0, "p10": 84.6, "p90": 117.8, "n": 5300},
    ("Retail", "Seoul"): {"median": 99.6, "p10": 77.7, "p90": 117.7, "n": 330},
    ("Retail", "Ulsan"): {"median": 97.6, "p10": 81.7, "p90": 113.5, "n": 5300},

    # RetailStripmall
    ("RetailStripmall", "Busan"): {"median": 180.5, "p10": 135.3, "p90": 225.8, "n": 3673},
    ("RetailStripmall", "Cheongju"): {"median": 178.5, "p10": 132.9, "p90": 222.9, "n": 3459},
    ("RetailStripmall", "Daegu"): {"median": 178.0, "p10": 132.9, "p90": 223.3, "n": 3812},
    ("RetailStripmall", "Daejeon"): {"median": 180.6, "p10": 135.1, "p90": 226.0, "n": 3749},
    ("RetailStripmall", "Gangneung"): {"median": 178.7, "p10": 132.9, "p90": 223.8, "n": 3391},
    ("RetailStripmall", "Gwangju"): {"median": 183.6, "p10": 137.9, "p90": 229.6, "n": 3230},
    ("RetailStripmall", "Incheon"): {"median": 176.5, "p10": 132.0, "p90": 221.7, "n": 3837},
    ("RetailStripmall", "Jeju"): {"median": 181.7, "p10": 137.1, "p90": 227.1, "n": 4078},
    ("RetailStripmall", "Seoul"): {"median": 179.5, "p10": 133.9, "p90": 225.2, "n": 3654},
    ("RetailStripmall", "Ulsan"): {"median": 179.0, "p10": 134.5, "p90": 224.7, "n": 3635},

    # School
    ("School", "Busan"): {"median": 177.3, "p10": 121.0, "p90": 238.3, "n": 693},
    ("School", "Cheongju"): {"median": 173.8, "p10": 119.3, "p90": 229.9, "n": 1000},
    ("School", "Daegu"): {"median": 172.1, "p10": 121.3, "p90": 228.9, "n": 169},
    ("School", "Daejeon"): {"median": 176.8, "p10": 124.3, "p90": 230.7, "n": 1569},
    ("School", "Gangneung"): {"median": 169.0, "p10": 98.9, "p90": 238.2, "n": 30},
    ("School", "Gwangju"): {"median": 181.6, "p10": 127.5, "p90": 234.2, "n": 1060},
    ("School", "Incheon"): {"median": 170.8, "p10": 134.3, "p90": 216.3, "n": 147},
    ("School", "Jeju"): {"median": 188.4, "p10": 103.4, "p90": 244.9, "n": 85},
    ("School", "Seoul"): {"median": 175.6, "p10": 120.9, "p90": 232.1, "n": 1500},
    ("School", "Ulsan"): {"median": 174.4, "p10": 120.9, "p90": 237.4, "n": 818},

    # SmallHotel
    ("SmallHotel", "Busan"): {"median": 113.8, "p10": 95.0, "p90": 135.4, "n": 1010},
    ("SmallHotel", "Cheongju"): {"median": 112.8, "p10": 93.4, "p90": 132.6, "n": 991},
    ("SmallHotel", "Daegu"): {"median": 112.8, "p10": 93.6, "p90": 131.3, "n": 852},
    ("SmallHotel", "Daejeon"): {"median": 113.9, "p10": 95.0, "p90": 133.1, "n": 1225},
    ("SmallHotel", "Gangneung"): {"median": 111.9, "p10": 94.3, "p90": 131.2, "n": 872},
    ("SmallHotel", "Gwangju"): {"median": 114.6, "p10": 96.4, "p90": 135.2, "n": 1047},
    ("SmallHotel", "Incheon"): {"median": 112.6, "p10": 93.8, "p90": 130.5, "n": 809},
    ("SmallHotel", "Jeju"): {"median": 114.2, "p10": 95.1, "p90": 133.3, "n": 815},
    ("SmallHotel", "Seoul"): {"median": 113.6, "p10": 93.8, "p90": 134.5, "n": 1118},
    ("SmallHotel", "Ulsan"): {"median": 112.9, "p10": 93.7, "p90": 133.0, "n": 999},

    # SmallOffice
    ("SmallOffice", "Busan"): {"median": 139.2, "p10": 100.3, "p90": 179.0, "n": 5300},
    ("SmallOffice", "Cheongju"): {"median": 137.9, "p10": 99.7, "p90": 177.4, "n": 5300},
    ("SmallOffice", "Daegu"): {"median": 137.5, "p10": 98.5, "p90": 177.7, "n": 5300},
    ("SmallOffice", "Daejeon"): {"median": 139.0, "p10": 100.3, "p90": 179.8, "n": 5300},
    ("SmallOffice", "Gangneung"): {"median": 138.3, "p10": 99.5, "p90": 177.8, "n": 5300},
    ("SmallOffice", "Gwangju"): {"median": 139.8, "p10": 101.4, "p90": 180.0, "n": 5300},
    ("SmallOffice", "Incheon"): {"median": 136.5, "p10": 99.4, "p90": 176.9, "n": 5300},
    ("SmallOffice", "Jeju"): {"median": 138.0, "p10": 100.1, "p90": 178.7, "n": 5300},
    ("SmallOffice", "Seoul"): {"median": 138.3, "p10": 100.4, "p90": 177.8, "n": 5300},
    ("SmallOffice", "Ulsan"): {"median": 138.9, "p10": 99.7, "p90": 178.9, "n": 5300},

    # Warehouse
    ("Warehouse", "Busan"): {"median": 39.0, "p10": 30.8, "p90": 47.4, "n": 5300},
    ("Warehouse", "Cheongju"): {"median": 39.3, "p10": 30.8, "p90": 47.9, "n": 5281},
    ("Warehouse", "Daegu"): {"median": 39.6, "p10": 31.0, "p90": 48.3, "n": 5300},
    ("Warehouse", "Daejeon"): {"median": 39.2, "p10": 30.9, "p90": 47.6, "n": 5300},
    ("Warehouse", "Gangneung"): {"median": 39.3, "p10": 30.8, "p90": 47.6, "n": 5300},
    ("Warehouse", "Gwangju"): {"median": 39.6, "p10": 31.3, "p90": 48.0, "n": 5300},
    ("Warehouse", "Incheon"): {"median": 39.1, "p10": 30.6, "p90": 47.7, "n": 5300},
    ("Warehouse", "Jeju"): {"median": 40.0, "p10": 31.5, "p90": 48.6, "n": 5300},
    ("Warehouse", "Seoul"): {"median": 39.8, "p10": 31.2, "p90": 48.4, "n": 5300},
    ("Warehouse", "Ulsan"): {"median": 39.1, "p10": 30.8, "p90": 47.5, "n": 5246},
}

# building-energy-3d 아키타입 → ems_transformer 건물 유형 매핑
# eui_lookup.get_eui()에서 신규 도시 보정에 사용
ARCHETYPE_TO_EMS: dict[str, str] = {
    "apartment_highrise": "Apartment",
    "apartment_midrise":  "Apartment",
    "hospital":           "Hospital",
    "hotel":              "Hotel",
    "office":             "LargeOffice",
    "retail":             "Retail",
    "school":             "School",
    "small_office":       "SmallOffice",
    "strip_mall":         "RetailStripmall",
    "university":         "School",
    "warehouse":          "Warehouse",
}

# 도시명 정규화 (소문자 → CITY_EUI_BASE 키 형식)
_CITY_NORMALIZE: dict[str, str] = {
    "seoul": "Seoul", "busan": "Busan", "daegu": "Daegu",
    "incheon": "Incheon", "gwangju": "Gwangju", "daejeon": "Daejeon",
    "ulsan": "Ulsan", "cheongju": "Cheongju", "gangneung": "Gangneung",
    "jeju": "Jeju",
}


def get_city_ratio(archetype: str, city: str, reference: str = "seoul") -> float | None:
    """도시 보정비 = CITY_EUI_BASE[arch, city].median / CITY_EUI_BASE[arch, reference].median.

    eui_lookup.get_eui()에서 신규 5개 도시의 EUI를 서울 기준값에 보정하는 데 사용.
    매핑 실패 또는 데이터 없을 때 None 반환 → 호출자가 서울 폴백 적용.
    """
    ems_b = ARCHETYPE_TO_EMS.get(archetype)
    if ems_b is None:
        return None
    city_key = _CITY_NORMALIZE.get(city)
    ref_key = _CITY_NORMALIZE.get(reference)
    if city_key is None or ref_key is None:
        return None
    ref_stats = CITY_EUI_BASE.get((ems_b, ref_key))
    tgt_stats = CITY_EUI_BASE.get((ems_b, city_key))
    if ref_stats is None or tgt_stats is None or ref_stats["median"] == 0:
        return None
    return round(tgt_stats["median"] / ref_stats["median"], 4)


# eui_lookup.py 호환 alias
get_city_factor = get_city_ratio
