"""Phase 4-B: ems_transformer E0 baseline에서 도시별 기준 EUI 추출.

ems_transformer gcs_download/all_metadata.jsonl (956K건) 중
EMS=E0 (베이스라인) 레코드만 필터링하여
building × city 조합별 EUI (kWh/m²·yr) 통계를 계산한다.

출력: src/simulation/city_eui_base.py

Usage:
    python scratch/extract_city_eui.py
"""
# scratch/ — 중간 파일, 작업 완료 후 삭제 가능
import json
import pathlib
import statistics
import sys

SCRATCH_DIR = pathlib.Path(__file__).parent
PROJECT_ROOT = SCRATCH_DIR.parent
OUTPUT_FILE = PROJECT_ROOT / "src" / "simulation" / "city_eui_base.py"

METADATA_PATH = pathlib.Path(
    "C:/Users/User/Desktop/myjob/8.simulation/ems_transformer/gcs_download/all_metadata.jsonl"
)

# ems_transformer 기준 건물 면적 (m²) — generate_qa_unified.py SSOT
BUILDING_AREA: dict[str, float] = {
    "Hotel":                11345.0,
    "MediumOffice":          4982.0,
    "LargeOffice":          46320.0,
    "School":               19592.0,
    "Retail":                2294.0,
    "Restaurant":             232.0,
    "Warehouse":             4835.0,
    "Apartment":             3135.0,
    "SmallOffice":            511.0,
    "FullServiceRestaurant":  511.0,
    "RetailStripmall":       2090.0,
    "PrimarySchool":         6871.0,
    "SmallHotel":            4014.0,
    "Hospital":             22422.0,
    "OutPatient":            3804.0,
}

JOULES_PER_KWH = 3_600_000.0


def main() -> None:
    print(f"[1/3] 메타데이터 로드: {METADATA_PATH}")
    buckets: dict[tuple[str, str], list[float]] = {}
    total = 0
    skipped = 0

    with open(METADATA_PATH, encoding="utf-8") as f:
        for line in f:
            rec = json.loads(line)
            total += 1

            # E0 (베이스라인) + valid 필터
            if rec.get("ems") != "E0":
                continue
            if not rec.get("validation", {}).get("valid", False):
                skipped += 1
                continue

            building = rec["building"]
            city = rec["city"]
            energy_j = rec["validation"]["energy_j"]

            area = BUILDING_AREA.get(building)
            if area is None:
                skipped += 1
                continue

            eui = (energy_j / JOULES_PER_KWH) / area
            key = (building, city)
            buckets.setdefault(key, []).append(eui)

    print(f"    전체 레코드: {total:,}")
    print(f"    E0 유효 버킷: {len(buckets)}, 스킵: {skipped}")

    print("[2/3] 통계 계산 (median / P10 / P90)...")
    results: dict[tuple[str, str], dict] = {}
    for (building, city), vals in sorted(buckets.items()):
        vals_sorted = sorted(vals)
        n = len(vals_sorted)
        med = statistics.median(vals_sorted)
        p10 = vals_sorted[max(0, int(n * 0.10) - 1)]
        p90 = vals_sorted[min(n - 1, int(n * 0.90))]
        results[(building, city)] = {
            "median": round(med, 1),
            "p10":    round(p10, 1),
            "p90":    round(p90, 1),
            "n":      n,
        }
        print(f"    ({building:22s}, {city:10s}) median={med:6.1f}  p10={p10:6.1f}  p90={p90:6.1f}  n={n}")

    print(f"[3/3] 출력: {OUTPUT_FILE}")
    lines = [
        "# AUTO-GENERATED by scratch/extract_city_eui.py",
        "# Source: ems_transformer E0 baseline (gcs_download/all_metadata.jsonl)",
        "# DO NOT EDIT MANUALLY — re-run extract_city_eui.py to regenerate",
        "#",
        f"# {len(results)}개 조합 (15 building × 10 city)",
        "# EUI 단위: kWh/m²·yr",
        "",
        "CITY_EUI_BASE: dict[tuple[str, str], dict] = {",
    ]

    current_building = None
    for (building, city), stats in sorted(results.items()):
        if building != current_building:
            if current_building is not None:
                lines.append("")
            lines.append(f"    # {building}")
            current_building = building
        lines.append(
            f'    ("{building}", "{city}"): '
            f'{{"median": {stats["median"]}, "p10": {stats["p10"]}, "p90": {stats["p90"]}, "n": {stats["n"]}}},'
        )

    lines.append("}")
    lines.append("")

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"    완료: {len(results)}개 조합 → {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
